import 'package:hive_flutter/hive_flutter.dart';

/// Hive service for local storage management
/// Handles initialization and provides access to different storage boxes
class HiveService {
  HiveService._();
  
  static final HiveService instance = HiveService._();
  
  // Box names
  static const String userBoxName = 'user_box';
  static const String documentsBoxName = 'documents_box';
  static const String annotationsBoxName = 'annotations_box';
  static const String signaturesBoxName = 'signatures_box';
  static const String preferencesBoxName = 'preferences_box';
  static const String usageBoxName = 'usage_box';
  
  // Boxes
  late Box<dynamic> _userBox;
  late Box<dynamic> _documentsBox;
  late Box<dynamic> _annotationsBox;
  late Box<dynamic> _signaturesBox;
  late Box<dynamic> _preferencesBox;
  late Box<dynamic> _usageBox;
  
  // Getters
  Box<dynamic> get userBox => _userBox;
  Box<dynamic> get documentsBox => _documentsBox;
  Box<dynamic> get annotationsBox => _annotationsBox;
  Box<dynamic> get signaturesBox => _signaturesBox;
  Box<dynamic> get preferencesBox => _preferencesBox;
  Box<dynamic> get usageBox => _usageBox;
  
  /// Initialize Hive and open all boxes
  Future<void> init() async {
    // Register adapters (will be generated by build_runner)
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(PDFDocumentAdapter());
    // Hive.registerAdapter(AnnotationAdapter());
    // Hive.registerAdapter(SignatureAdapter());
    
    // Open boxes
    _userBox = await Hive.openBox<dynamic>(userBoxName);
    _documentsBox = await Hive.openBox<dynamic>(documentsBoxName);
    _annotationsBox = await Hive.openBox<dynamic>(annotationsBoxName);
    _signaturesBox = await Hive.openBox<dynamic>(signaturesBoxName);
    _preferencesBox = await Hive.openBox<dynamic>(preferencesBoxName);
    _usageBox = await Hive.openBox<dynamic>(usageBoxName);
  }
  
  /// Clear all data from all boxes
  Future<void> clearAll() async {
    await _userBox.clear();
    await _documentsBox.clear();
    await _annotationsBox.clear();
    await _signaturesBox.clear();
    await _preferencesBox.clear();
    await _usageBox.clear();
  }
  
  /// Close all boxes
  Future<void> close() async {
    await Hive.close();
  }
  
  // ============== User Methods ==============
  
  Future<void> saveUser(Map<String, dynamic> userData) async {
    await _userBox.put('current_user', userData);
  }
  
  Map<String, dynamic>? getUser() {
    final data = _userBox.get('current_user');
    return data != null ? Map<String, dynamic>.from(data) : null;
  }
  
  Future<void> deleteUser() async {
    await _userBox.delete('current_user');
  }
  
  // ============== Preferences Methods ==============
  
  Future<void> savePreference(String key, dynamic value) async {
    await _preferencesBox.put(key, value);
  }
  
  T? getPreference<T>(String key, {T? defaultValue}) {
    return _preferencesBox.get(key, defaultValue: defaultValue) as T?;
  }
  
  // ============== Usage Methods ==============
  
  Future<void> saveUsageStats(Map<String, dynamic> stats) async {
    await _usageBox.put('stats', stats);
  }
  
  Map<String, dynamic>? getUsageStats() {
    final data = _usageBox.get('stats');
    return data != null ? Map<String, dynamic>.from(data) : null;
  }
  
  Future<void> incrementUsageCount(String featureKey) async {
    final stats = getUsageStats() ?? {};
    final currentCount = stats[featureKey] as int? ?? 0;
    stats[featureKey] = currentCount + 1;
    await saveUsageStats(stats);
  }
  
  int getUsageCount(String featureKey) {
    final stats = getUsageStats();
    return stats?[featureKey] as int? ?? 0;
  }
  
  // ============== Dark Mode ==============
  
  Future<void> setDarkMode(bool isDarkMode) async {
    await _preferencesBox.put('dark_mode', isDarkMode);
  }
  
  bool? getDarkMode() {
    return _preferencesBox.get('dark_mode');
  }
}
